"""
Django settings for bjarne_dev project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
#STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "static_root") 
#STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static") 
STATIC_ROOT = "/home/bjarxxjd/public_html/static" 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
except KeyError as e:
    SECRET_KEY = 'django-insecure-4vm+3676-5s4wvexnc(n)@+l+dlet$2^-&0@or!clg)z!i$#6)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "1"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "bjarne.dev", "www.bjarne.dev"]

if DEBUG:
    CSRF_TRUSTED_ORIGINS = ['http://localhost','http://*.127.0.0.1']
    ALLOWED_HOSTS.append('*')
    os.environ["DJANGO_RUNSERVER_HIDE_WARNING"] = "true" # supress this annoyance in new Django version

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'urlshort.apps.UrlshortConfig',
    'index.apps.IndexConfig',
    #'filelink.apps.FilelinkConfig',
    'photo.apps.PhotoConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bjarne_dev.urls'
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")  # ROOT dir for templates

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bjarne_dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'MET'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# by default csrf failure doesnt automatically use 403.html
CSRF_FAILURE_VIEW = "index.views.csrf_failure"

# ---------------------------------------------------------------------------
# FileLink
# ---------------------------------------------------------------------------
# per-upload size caps, global storage cap, and rate-limit windows
FILELINK_PER_FILE_BYTES = int(os.environ.get('FILELINK_PER_FILE_BYTES', 100 * 1024 * 1024)) # 100 MB
FILELINK_PER_TXT_BYTES = int(os.environ.get('FILELINK_PER_TXT_BYTES', 1 * 1024 * 1024)) # 1 MB
FILELINK_GLOBAL_BYTES = int(os.environ.get('FILELINK_GLOBAL_BYTES', 15 * 1024 ** 3)) # 15 GB
FILELINK_DISK_RESERVE_BYTES = int(os.environ.get('FILELINK_DISK_RESERVE_BYTES', 1 * 1024 ** 3)) # 1 GB
FILELINK_UPLOAD_RATE = int(os.environ.get('FILELINK_UPLOAD_RATE', 30)) # 30 uploads per hour
FILELINK_BLOB_RATE = int(os.environ.get('FILELINK_BLOB_RATE', 1000)) # blob requests per hour

# cap multipart bodies so worker memory is not wasted before
# the views own size check fires
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # forms (non-file) cap 2MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # spill to disk above this

# cross-worker shared cache used for rate-limit + failure counters.
# MAX_ENTRIES is a backstop only: Django reaps expired files lazily, cleanup advised (purge_expired)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'media', '.cache'),
        'TIMEOUT': 3600,
        'OPTIONS': {'MAX_ENTRIES': 1000},
    },
}

# tighter referrer policy for the whole site
SECURE_REFERRER_POLICY = 'same-origin'

# ---------------------------------------------------------------------------
# Photo portfolio
# ---------------------------------------------------------------------------
# the derivatives are written straight into
# a directory the webserver already serves: in production that is
# public_html/static, so image bytes never round-trip through Python. In
# DEBUG they sit under MEDIA_ROOT and runserver serves them (see urls.py)
if DEBUG:
    PHOTO_STORAGE_DIR = os.path.join(BASE_DIR, 'media', 'photo')
    PHOTO_STORAGE_URL = '/media/photo/'
else:
    PHOTO_STORAGE_DIR = os.path.join(STATIC_ROOT, 'photo')
    PHOTO_STORAGE_URL = '/static/photo/'

# longest-edge caps (px), AVIF quality and encode speed for derivatives
PHOTO_THUMB_EDGE = int(os.environ.get('PHOTO_THUMB_EDGE', 900))
PHOTO_LARGE_EDGE = int(os.environ.get('PHOTO_LARGE_EDGE', 2560))
PHOTO_AVIF_QUALITY = int(os.environ.get('PHOTO_AVIF_QUALITY', 65))
PHOTO_AVIF_SPEED = int(os.environ.get('PHOTO_AVIF_SPEED', 4))  # 0 slowest/best, 10 fastest
