"""
Django settings for bjarne_dev project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CORE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# load variables from file if possible
load_dotenv(BASE_DIR / ".env")
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)
#STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_in_env", "static_root") 
#STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static") 
STATIC_ROOT = "/home/bjarxxjd/public_html/static" 

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
try:
    SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]
except KeyError as e:
    SECRET_KEY = 'django-insecure-4vm+3676-5s4wvexnc(n)@+l+dlet$2^-&0@or!clg)z!i$#6)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "") == "1"

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "bjarne.dev", "www.bjarne.dev"]

if DEBUG:
    CSRF_TRUSTED_ORIGINS = ['http://localhost','http://*.127.0.0.1']
    ALLOWED_HOSTS.append('*')
    os.environ["DJANGO_RUNSERVER_HIDE_WARNING"] = "true" # supress this annoyance in new Django version

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'urlshort.apps.UrlshortConfig',
    'index.apps.IndexConfig',
    #'filelink.apps.FilelinkConfig',
    'photo.apps.PhotoConfig',
    'webring_gif.apps.WebringGifConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bjarne_dev.urls'
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")  # ROOT dir for templates

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bjarne_dev.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'MET'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# by default csrf failure doesnt automatically use 403.html
CSRF_FAILURE_VIEW = "index.views.csrf_failure"

# ---------------------------------------------------------------------------
# FileLink
# ---------------------------------------------------------------------------
# per-upload file size caps. past a few hundred MB also needs the webserver's own request-body limit
# raised to PART_BYTES
FILELINK_PER_FILE_BYTES = int(os.environ.get('FILELINK_PER_FILE_BYTES', 512 * 1024 ** 2)) # 512 MB
FILELINK_GLOBAL_BYTES = int(os.environ.get('FILELINK_GLOBAL_BYTES', 12 * 1024 ** 3)) # 12 GB
FILELINK_DISK_RESERVE_BYTES = int(os.environ.get('FILELINK_DISK_RESERVE_BYTES', 1 * 1024 ** 3)) # 1 GB
# ceiling on bytes tied up by uploads still in flight
FILELINK_STAGING_BYTES = int(os.environ.get('FILELINK_STAGING_BYTES', 4 * 1024 ** 3)) # 4 GB

# client-side AES-GCM frame. overhead at 8 KB per 2 GB
FILELINK_FRAME_BYTES = int(os.environ.get('FILELINK_FRAME_BYTES', 4 * 1024 ** 2)) # 4 MiB
# bytes per part request. bound for how much webserver buffer holds at once
# independent of file size. Must be a multiple of 16!!
FILELINK_PART_BYTES = int(os.environ.get('FILELINK_PART_BYTES', 8 * 1024 ** 2)) # 8 MiB
# slack over PART_BYTES allowed on a part body
FILELINK_PART_SLACK_BYTES = int(os.environ.get('FILELINK_PART_SLACK_BYTES', 4096))

# how long untracked files sit before collected by purge. has to outlast part upload time
FILELINK_ORPHAN_GRACE_SECONDS = int(os.environ.get('FILELINK_ORPHAN_GRACE_SECONDS', 3600))
# must stay >= longest TTL any cache key uses
FILELINK_CACHE_GRACE_SECONDS = int(os.environ.get('FILELINK_CACHE_GRACE_SECONDS', 7200))

# cap multipart bodies so worker memory is not wasted before
# the views own size check fires
DATA_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # forms (non-file) cap 2MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 2 * 1024 * 1024  # spill to disk above this

# cross-worker shared cache used for rate-limit + failure counters.
# MAX_ENTRIES is a backstop only: Django reaps expired files lazily, cleanup advised (purge_expired)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'media', '.cache'),
        'TIMEOUT': 3600,
        'OPTIONS': {'MAX_ENTRIES': 1000},
    },
    # rate-limit counters, isolated from default cache
    'ratelimit': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': os.path.join(BASE_DIR, 'media', '.cache-rl'),
        'TIMEOUT': 7200,
        'OPTIONS': {'MAX_ENTRIES': 5000},
    },
}

# tighter referrer policy for the whole site
SECURE_REFERRER_POLICY = 'same-origin'

# ---------------------------------------------------------------------------
# Rate limits (per hour is default)
# ---------------------------------------------------------------------------
RATELIMIT_IP_HEADER = os.environ.get('RATELIMIT_IP_HEADER') or None  # None: use REMOTE_ADDR

URLSHORT_CREATE_IP_RATE = int(os.environ.get('URLSHORT_CREATE_IP_RATE', 25))
URLSHORT_CREATE_RATE = int(os.environ.get('URLSHORT_CREATE_RATE', 250))

INDEX_VISIT_IP_RATE = int(os.environ.get('INDEX_VISIT_IP_RATE', 100))
INDEX_VISIT_RATE = int(os.environ.get('INDEX_VISIT_RATE', 1000))

# bound resolver traffic, page loads are cached
IP_RDNS_IP_RATE = int(os.environ.get('IP_RDNS_IP_RATE', 60))
IP_RDNS_RATE = int(os.environ.get('IP_RDNS_RATE', 600))

# filelink rate limits
FILELINK_UPLOAD_IP_RATE = int(os.environ.get('FILELINK_UPLOAD_IP_RATE', 10))
FILELINK_UPLOAD_RATE = int(os.environ.get('FILELINK_UPLOAD_RATE', 100))
# part budget is upload budget multiplied out. Raise alongside PER_FILE_BYTES.
FILELINK_PART_IP_RATE = int(os.environ.get('FILELINK_PART_IP_RATE', 5000))
FILELINK_PART_RATE = int(os.environ.get('FILELINK_PART_RATE', 50000))
FILELINK_BLOB_IP_RATE = int(os.environ.get('FILELINK_BLOB_IP_RATE', 1200))
FILELINK_BLOB_RATE = int(os.environ.get('FILELINK_BLOB_RATE', 10000))

# ---------------------------------------------------------------------------
# Photo portfolio
# ---------------------------------------------------------------------------
# derivatives are written straight into public_html/static
# In DEBUG they sit under MEDIA_ROOT and runserver serves them (see urls.py)
if DEBUG:
    PHOTO_STORAGE_DIR = os.path.join(BASE_DIR, 'media', 'photo')
    PHOTO_STORAGE_URL = '/media/photo/'
else:
    PHOTO_STORAGE_DIR = os.path.join(STATIC_ROOT, 'photo')
    PHOTO_STORAGE_URL = '/static/photo/'

# longest-edge caps (px), AVIF quality and encode speed for derivatives
PHOTO_THUMB_EDGE = int(os.environ.get('PHOTO_THUMB_EDGE', 900))
PHOTO_LARGE_EDGE = int(os.environ.get('PHOTO_LARGE_EDGE', 2560))
PHOTO_AVIF_QUALITY = int(os.environ.get('PHOTO_AVIF_QUALITY', 65))
PHOTO_AVIF_SPEED = int(os.environ.get('PHOTO_AVIF_SPEED', 4))  # 0 slowest/best, 10 fastest
