# Generated by Django 5.1.1 on 2026-07-16 20:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_id', models.CharField(db_index=True, max_length=8, unique=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('capture_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('camera', models.CharField(blank=True, max_length=120)),
                ('lens', models.CharField(blank=True, max_length=120)),
                ('focal_length', models.CharField(blank=True, max_length=32)),
                ('aperture', models.CharField(blank=True, max_length=32)),
                ('shutter_speed', models.CharField(blank=True, max_length=32)),
                ('iso', models.PositiveIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('published', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('orientation', models.CharField(blank=True, choices=[('landscape', 'landscape'), ('portrait', 'portrait'), ('square', 'square')], max_length=10)),
                ('version', models.PositiveIntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photographs', to='photo.collection')),
            ],
            options={
                'ordering': ['collection', 'display_order', '-capture_date'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='photo.photograph'),
        ),
    ]
