# Generated by Django 5.1.1 on 2025-04-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorted_url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.TextField(max_length=1024, unique=True)),
                ('hash', models.CharField(max_length=10, unique=True)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
            ],
        ),
    ]
