# Generated by Django 5.1.1 on 2025-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshort', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorted_url',
            name='original_url',
            field=models.TextField(max_length=2048, unique=True),
        ),
    ]
